quiz/urls.py
from django.contrib import admin
from django.urls import path
# from LearnAJAX import views as a
# from Quiz import views
from .views import welcom, quiz, result, show
from django.conf import settings
from django.conf.urls.static import static

app_name = 'quiz'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcom, name='welcom'),
    path('quiz/', quiz, name='quiz'),
    path('result/', result, name='result'),
    path('showAnswer/', show, name='show'),
    ]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('chitchat/', include('chitChat.urls')),
    path('artikel/', include('artikel.urls', namespace='artikel')),
    path('forum/', include('forum.urls')),
    path('polling/', include('polling.urls', namespace='polling')),
]

quiz/models.py
from django.db import models

# Create your models here.

class Questions(models.Model):
    question = models.CharField(max_length=300, null=True)
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option3 = models.CharField(max_length=200)
    option4 = models.CharField(max_length=200)
    answer = models.CharField(max_length=200)

    def __str__(self):
        return self.question

class Answer(models.Model):
    nama = models.CharField(max_length=100)
    result = models.IntegerField(null=True)
    ans1 = models.CharField(max_length=200, null=True)
    ans2 = models.CharField(max_length=200, null=True)
    ans3 = models.CharField(max_length=200, null=True)
    ans4 = models.CharField(max_length=200, null=True)
    ans5 = models.CharField(max_length=200, null=True)
    ans6 = models.CharField(max_length=200, null=True)
    ans7 = models.CharField(max_length=200, null=True)
    ans8 = models.CharField(max_length=200, null=True)
    ans9 = models.CharField(max_length=200, null=True)
    ans10 = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.nama

quiz/forms.py
from django import forms
from .models import Answer, Questions

ans1 = [
    ('mahkota', 'Mahkota'),
    ('dermaga', 'Dermaga'),
    ('virus', 'Virus'),
    ('bunga', 'Bunga'),
]

ans2 = [
    ('a', 'Mencuci tangan secara rutin.'),
    ('b', 'Selalu jaga jarak aman dengan orang yang batuk atau bersin.'),
    ('c', 'Jangan sentuh mata, hidung, atau mulut Anda.'),
    ('d', 'Jalan-jalan ke mall karena bosan di rumah saja.'),
]

ans3 = [
    ('a', 'Mandi.'),
    ('b', 'Pergi keluar rumah.'),
    ('c', 'Tidur'),
    ('d', 'Pembelajaran dirumah.'),
]

ans4 = [
    ('a', 'Gunakan masker.'),
    ('b', 'Patuhi etika batuk/bersin yang benar. Caranya, menutup mulut dan hidung dengan tisu atau punggung lengan.'),
    ('c', 'Mengenakan APD(alat pelindung diri) dan payung.'),
    ('d', 'Upayakan tidak menggunakan transportasi massal.'),
]

ans5 = [
    ('a', 'Akan dirujuk ke salah satu rumah sakit (RS) rujukan yang siap untuk penanganan Covid-19.'),
    ('b', 'Akan diantar ke RS rujukan menggunakan ambulans didampingi oleh nakes yang menggunakan alat pelindung diri (APD).'),
    ('c', 'Di RS rujukan akan dilakukan pengambilan spesimen untuk pemeriksaan laboratorium dan dirawat di ruang isolasi.'),
    ('d', 'Akan diperintahkan oleh nakes untuk pergi berlibur.')
]

ans6 = [
    ('a', 'Screening'),
    ('b', 'Streaming'),
    ('c', 'Dancing'),
    ('d', 'Parking'),
]

ans7 = [
    ('a', 'Menggunakan topi.'),
    ('b', 'Pembatasan fisik dan kebersihan tangan.'),
    ('c', 'Minum larutan oralit.'),
    ('d', 'Wajib menggunakan masker N95.'),
]

ans8 = [
    ('a', '911'),
    ('b', '081'),
    ('c', '119'),
    ('d', '021')
]

ans9 = [
    ('a', '1 hari saja'),
    ('b', '2 hari'),
    ('c', '30 hari'),
    ('d', '14 hari'),
]

ans10 = [
    ('a', 'Masker bedah'),
    ('b', 'Masker kain'),
    ('c', 'Masker buff'),
    ('d', 'Masker N95'),
]

class FormQuestion(forms.Form):
    nama = forms.CharField(
        label="Your Name",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-60',
            }
        )
    )

    question1 = forms.CharField(
        label='Kata ‘Corona’ berasal dari bahasa Latin yang memiliki arti?', 
        widget=forms.RadioSelect(choices=ans1))

    question2 = forms.CharField(
        label='Berikut ini merupakan cara mencegah penyebaran Covid 19, kecuali.', 
        widget=forms.RadioSelect(choices=ans2))

    question3 = forms.CharField(
        label='Diwajibkan untuk menggunakan masker, saat...', 
        widget=forms.RadioSelect(choices=ans3))

    question4 = forms.CharField(
        label='Saat berobat atau memeriksakan diri ke fasilitas pelayanan kesehatan, Anda harus melakukan beberapa hal dibawah ini, kecuali.', 
        widget=forms.RadioSelect(choices=ans4))  

    question5 = forms.CharField(
        label='Jika seseorang kriteria Covid-19, maka akan dilakukan tahapan berikut, kecuali.', 
        widget=forms.RadioSelect(choices=ans5))  
    
    question6 = forms.CharField(
        label='Ketika menjalani pemeriksaan di pelayanan kesehatan, petugas kesehatan akan melakukan...', 
        widget=forms.RadioSelect(choices=ans6))  

    question7 = forms.CharField(
        label='Mengenakan masker saja tidak cukup untuk melindungi diri dari COVID-19, sehingga harus dikombinasikan dengan...', 
        widget=forms.RadioSelect(choices=ans7))   
    
    question8 = forms.CharField(
        label='Masyarakat bisa mengakses layanan ... untuk laporan gawat darurat masalah kesehatan.', 
        widget=forms.RadioSelect(choices=ans8))  

    question9 = forms.CharField(
        label='Masa inkubasi COVID-19 diperkirakan antara 1 sampai...', 
        widget=forms.RadioSelect(choices=ans9))  

    question10 = forms.CharField(
        label='Tiga jenis masker yang direkomendasikan oleh Kementerian Kesehatan, yakni, kecuali.', 
        widget=forms.RadioSelect(choices=ans10))  

    

quiz/views.py
from django.shortcuts import render, redirect
from .models import Questions, Answer
from .forms import FormQuestion
from django.http import HttpResponseRedirect
# from django.core.paginator import Paginator
# Create your views here.



def welcom(request):
    return render(request, 'quiz/welcom.html')

def quiz(request):
    form_question = FormQuestion(request.POST or None)
    if (form_question.is_valid() and request.method == 'POST'):
        cd = form_question.cleaned_data
        Answer.objects.create(
            nama = cd['nama'],
            ans1 = cd['question1'],
            ans2 = cd['question2'],
            ans3 = cd['question3'],
            ans4 = cd['question4'],
            ans5 = cd['question5'],
            ans6 = cd['question6'],
            ans7 = cd['question7'],
            ans8 = cd['question8'],
            ans9 = cd['question9'],
            ans10 = cd['question10'],
        )
        return redirect('quiz:result')
    context = {
        'form_question':form_question,
    }


    return render(request, 'quiz/quiz.html', context)

def result(request):
    score = 0
    ques = Answer.objects.latest('id')

    if ques.ans1 == "mahkota" :
        score += 1
    if ques.ans2 == 'd' :
        score += 1
    if ques.ans3 == 'b' :
        score += 1
    if ques.ans4 == 'c' :
        score += 1
    if ques.ans5 == 'd' :
        score += 1
    if ques.ans6 == 'a' :
        score += 1
    if ques.ans7 == 'b' :
        score += 1
    if ques.ans8 == 'c' :
        score += 1
    if ques.ans9 == 'd' :
        score += 1
    if ques.ans10 == 'c' :
        score += 1


    ques.result = score
    ques.save()
    orang = Answer.objects.all()
    context = {
        'orang':orang,
        'orangbaru' : ques,
    }

    return render(request, 'quiz/results.html', context)

def show(request):
    ques = Questions.objects.all()
    return render(request, 'quiz/show.html', {'ques':ques})

quiz/templates/quiz/quiz.html
{% extends 'base.html' %} {% load static %} {% block css %}
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <title>Quiz Page</title> 
{% endblock css %} {% block main %}

    <section class="kuis" id="kuis">
        <form method="post">
            {% csrf_token %}

        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 mt-5 p-4 m-p mx-auto">
                    <div class="form-group">
                        <div style="display: block;" class="col-md-5">
                            <h3 style="color: #8cd498;"><b>{{form_question.nama.label_tag}}</b></h3>
                            {{form_question.nama}}
                        </div>
                    </div>    
            </div>
        </div>

        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">
                    <div class="ques m-3">
                        <h6>Question 1</h6>
                        <h3>{{ form_question.question1.label }}</h3>
                        {% for radio in form_question.question1 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
            
        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">
                    <div class="ques m-3">
                        <h6>Question 2</h6>
                        <h3>{{ form_question.question2.label }}</h3>
                        {% for radio in form_question.question2 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>

        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">
                    <div class="ques m-3">
                        <h6>Question 3</h6>
                        <h3>{{ form_question.question3.label }}</h3>
                        {% for radio in form_question.question3 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">
                    <div class="ques m-3">
                        <h6>Question 4</h6>
                        <h3>{{ form_question.question4.label }}</h3>
                        {% for radio in form_question.question4 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">
                    <div class="ques m-3">
                        <h6>Question 5</h6>
                        <h3>{{ form_question.question5.label }}</h3>
                        {% for radio in form_question.question5 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">    
                    <div class="ques m-3"> 
                        <h6>Question 6</h6>
                        <h3>{{ form_question.question6.label }}</h3>
                        {% for radio in form_question.question6 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">
                    <div class="ques m-3">
                        <h6>Question 7</h6>
                        <h3>{{ form_question.question7.label }}</h3>
                        {% for radio in form_question.question7 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">
                    <div class="ques m-3">
                        <h6>Question 8</h6>
                        <h3>{{ form_question.question8.label }}</h3>
                        {% for radio in form_question.question8 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">
                    <div class="ques m-3">
                        <h6>Question 9</h6>
                        <h3>{{ form_question.question9.label }}</h3>
                        {% for radio in form_question.question9 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8 m-p mx-auto">
                    <div class="ques m-3">
                        <h6>Question 10</h6>
                        <h3>{{ form_question.question10.label }}</h3>
                        {% for radio in form_question.question10 %}
                        <div class="col m-3">
                                <div class="radio">
                                    {{ radio }}
                                </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
        <div class="row m-5 mt-3 justify-content-center">
            <div id="kuisnya" class="col-md-8m-p mx-auto">

                    <a href="" class="btnNama">
                        <button style="background-color: #B7FFC2; color: #4c7e54;" id="tombol" class="btn"  type="submit">Submit Answer</button>
                    </a>
            </div>
        </div>
    </form>
        <div class="row mt-5 justify-content-center">
            <div class="col text-center">
                <h4>Jawablah semua pertanyaan diatas!</h4>
            </div>
        </div>
       
    </section>
    <div class="row mt-5">
        <div class="col-md-2 col-sm-2"></div>
        <div class="col-md-3 col-sm-3 text-center">
            <img id="atas" src="{% static 'danger.png' %}" class="object-fit-contain" alt="~" width="70px"><br>
        </div>
    </div>

    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

{% endblock main %}

quiz/templates/quiz/results.html
{% extends 'base.html' %} {% load static %} {% block css %}
    <title>Result Page</title>
    <link rel="stylesheet" href="{% static 'style.css' %}"></head>
    <title>Quiz result</title>
{% endblock css %} {% block main %}
    <div class="result">
        <div class="row mt-5 mb-3 justify-content-center">
            <div class="col-md-5 mt-3 text-center">
                <h3>Hello {{ orangbaru.nama }}!</h3>
                <a href="{% url 'quiz:show' %}"><h3>Your Score : {{orangbaru.result}} / 10</h3></a>
                <p>Tap the score to see all the right answer</p>
                <img id="atas" src="{% static 'virus.png' %}" class="object-fit-contain" alt="~" width="50px"> <br>
            </div>
        </div>
    </div>

    <div class="row m-5">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Score</th>
                </tr>
            </thead>
            <tbody>
                {% for nama in orang %}
                <tr>
                    <td>{{nama.nama}}</td>
                    <td>{{nama.result}}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>

    <div class="attempt">
        <div class="row mt-5 mb-3 justify-content-center">
            <div class="col-md-12 text-center">
                <button id="Start" type="button" class="btn btn-lg"><a href="{% url 'quiz:show' %}">Lihat jawaban benar!</a></button>          
            </div>
        </div>
    </div>

    <div class="row mb-3 justify-content-center">
        <div class="col text-center">
            <img id="atas" src="{% static 'coronavirus.png' %}" class="object-fit-contain" alt="~" width="50px">
        </div>
    </div>
{% endblock main %}

quiz/templates/quiz/show.html
{% extends 'base.html' %} {% load static %} {% block css %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>See the right answer</title>
{% endblock css %} {% block main %}

<section class="show">
    <div class="row m-5 justify-content-center">
        <div class="col mt-3 text-center">
            <h2>Pertanyaan dan Jawaban Benar</h2>
            <img id="atas" src="{% static 'virus.png' %}" class="object-fit-contain" alt="~" width="50px"> <br>
        </div>
    </div>
    <div class="row m-5 justify content-center">
        <div class="row">
            {% for i in ques %}
            <div class="card m-3">
                <div class="card-header">
                    <h4><b>{{ i.question }}</b></h4>
                </div>
                <div class="card-body">
                  <blockquote class="blockquote mb-0">
                    <h5>{{ i.answer }}</h5>
                  </blockquote>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>

    <div class="attempt">
        <div class="row mt-5 mb-3 justify-content-center">
            <div class="col-md-12 text-center">
                <button id="Start" type="button" class="btn btn-lg"><a href="{% url 'quiz:welcom' %}">Back to Quiz Page!</a></button>          
            </div>
        </div>
    </div>
</section>
{% endblock main %}

quiz/templates/quiz/welcom.html
{% extends 'base.html' %} {% load static %} {% block css %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Welcome to Quiz!</title>
{% endblock css %} {% block main %}

<section class="welcom">

    <div class="text">
        <div class="row mt-5 justify-content-center">
            <div class="col-md-2 text-center" >
            </div>
            <div class="col-md-5 col-sm-7 mt-3 text-center">
              <h3>Sejauh Mana Pengetahuanmu Mengenai Covid 19?</h3>
            </div>
            <div class="col-md-2 col-sm-2 mt-3 text-center">
                <img id="atas" src="{% static 'coronavirus.png' %}" class="object-fit-contain" alt="~" width="60px">
            </div>
        </div>
        <div class="row mt-3 justify-content-center">
            <div class="col-md-2 col-sm-2 text-center" >
                <img id="atas" src="{% static 'virus.png' %}" class="object-fit-contain" alt="~" width="70px"> 
                <img id="atas" src="{% static 'man.png' %}" class="object-fit-contain" alt="~" width="70px"> 
                <img id="atas" src="{% static 'hand-wash.png' %}" class="object-fit-contain" alt="~" width="70px">
                <img id="atas" src="{% static 'pneumonia.png' %}" class="object-fit-contain" alt="~" width="70px">
                <img id="atas" src="{% static 'keep-distance.png' %}" class="object-fit-contain" alt="~" width="70px">
                <img id="atas" src="{% static 'ambulance.png' %}" class="object-fit-contain" alt="~" width="70px">
            </div>
            <div id="textnya" class="col-md-7 col-sm-10 p-5">
                <p>&emsp;&emsp;Menurut dr. Devia Irine Putri dari <i>KlikDokter</i>, virus ini sebenarnya masih satu keluarga dengan MERS (<i>Middle East Respiratory Syndrome</i>) dan SARS (<i>Severe Acute Respiratory Syndrom</i>e). Sebagai informasi, kata corona pada virus tersebut berasal dari bahasa Latin yang berarti <b>mahkota</b>. Dinamakan corona sesuai dengan bentuk virus tersebut yang jika dilihat menggunakan mikroskop tampak seperti mahkota. Terkait gejalanya, corona virus menyerupai flu biasa, seperti demam, batuk. Hanya saja, virus ini biasanya menyebabkan penderitanya mengalami sesak napas alias sangat susah bernapas. Sampai kalau parah bisa menyebabkan pneumonia, infeksi di paru-paru. Namun, ada juga orang-orang yang tidak memiliki gejala apapun.</p>
                <p>Untuk mencegah penyebaran COVID-19, lakukan beberapa cara dibawah ini</p>
                <p>1. Cuci tangan Anda secara rutin. Gunakan sabun dan air, atau cairan pembersih tangan berbahan alkohol.</p>
                <p>2. Selalu jaga jarak aman dengan orang yang batuk atau bersin.</p>
                <p>3. Kenakan masker jika pembatasan fisik tidak dimungkinkan.</p>
                <p>4. Jangan sentuh mata, hidung, atau mulut Anda.</p>
                <p>5. Saat batuk atau bersin, tutup mulut dan hidung Anda dengan lengan atau tisu.</p>
                <p>6. Jangan keluar rumah jika merasa tidak enak badan.</p>
                <p>7. Jika demam, batuk, atau kesulitan bernapas, segera cari bantuan medis.</p>
                <p>8. Telepon terlebih dahulu agar penyedia layanan kesehatan dapat segera mengarahkan Anda ke fasilitas kesehatan yang tepat. Tindakan ini akan melindungi Anda serta mencegah penyebaran virus dan infeksi lainnya.</p>
                <p>9. Selalu menggunakan masker jika akan keluar rumah.</p>
                <p>Mengenakan masker saja tidak cukup untuk melindungi diri dari COVID-19, sehingga harus dikombinasikan dengan pembatasan fisik dan kebersihan tangan. Tiga jenis masker yang direkomendasikan oleh Kementerian Kesehatan, yakni masker N95, masker bedah, dan masker kain. Ikuti saran yang diberikan oleh otoritas kesehatan setempat.</p>
                
                <p>Mengacu pada Protokol Kesehatan Penanganan Covid-19 yang dikeluarkan Kementerian Kesehatan, berikut beberapa hal yang harus Anda perhatikan pada pertolongan pertama Covid 19: </p>
                <p><b>Jika kondisi sehat</b></p>
                <p>Meski kondisi tubuh Anda sehat, perhatikan beberapa hal berikut ini: </p>
                <p>1. Ada riwayat perjalanan 14 hari yang lalu (masa inkubasi COVID-19 diperkirakan antara 1-14 hari), ke negara atau daerah yang terjangkit Covid-19, maka sebaiknya Anda menghubungi <i>hotline center</i> 119 <i>ext</i> 9 untuk mendapatkan petunjuk lebih lanjut. <br>
                2. Pasca-merebaknya wabah virus corona di Indonesia, sejumlah daerah juga menerapkan prosedur bagi mereka yang yang datang atau baru pulang dari wilayah terjangkit virus corona. Prosedur itu beragam, ada yang meminta agar melapor ke pengurus RT setempat, ada pula yang meminta memeriksakan diri ke Puskesmas. Pastikan hal ini kepada pihak berwenang di wilayah yang Anda datangi sebagai langkah antisipatif. <br>
                3. Anda juga diminta berkonsultasi melalui <i>hotline</i> 119 <i>ext</i> 9 meski kondisi tubuh sehat, jika memiliki riwayat pernah kontak dengan penderita atau pasien yang sudah dinyatakan positif Covid-19.</p>
            
                <p><b>Jika kondisi tidak sehat</b></p>
                <p>Istirahat dan minum yang cukup, jika Anda merasa tidak sehat dengan kriteria seperti di bawah ini:</p>
                <p>1. Demam 38 derajat Celcius Menderita batuk/pilek<br>
                2. Jika kondisi Anda disertai dengan kesulitan bernapas (sesak atau napas cepat), segera periksa atau berobat ke fasilitas pelayanan kesehatan (fasyankes). </p>
                
                <p>Saat berobat atau memeriksakan diri ke fasilitas pelayanan kesehatan, Anda harus melakukan ini:</p>
                <p>1. Gunakan masker<br>
                2. Jika tidak memiliki masker, patuhi etika batuk/bersin yang benar. Caranya, menutup mulut dan hidung dengan tisu atau punggung lengan <br>
                3. Upayakan tidak menggunakan transportasi massal.</p>

                <p>Ketika menjalani pemeriksaan di pelayanan kesehatan, petugas kesehatan akan melakukan <i>screening</i>: </p>
                <p><b>Jika memenuhi kriteria suspect Covid-19</b></p>
                <p>1. Anda akan dirujuk ke salah satu rumah sakit (RS) rujukan yang siap untuk penanganan Covid-19. <br>
                2. Anda akan diantar ke RS rujukan menggunakan ambulans didampingi oleh nakes yang menggunakan alat pelindung diri (APD). <br>
                3. Di RS rujukan akan dilakukan pengambilan spesimen untuk pemeriksaan laboratorium dan dirawat di ruang isolasi.
                </p>

                <p><b>Jika tidak memenuhi kriteria suspect Covid-19</b></p>
                <p>Anda akan dirawat inap atau rawat jalan tergantung diagnosa dan keputusan dokter fasyankes.</p>

                <p>Sumber:</p>
                <p><u>//www.kompas.com</u> <br>
                    <u>https://www.who.int/emergencies/</u><br>
                    <u>https://www.klikdokter.com/ </u>
                </p>
            </div>
        </div>
    </div>
    
    <div class="attempt">
        <div class="row mt-5 mb-3 justify-content-center">
            <div class="col-md-12 text-center">
                <button id="Start" type="button" class="btn btn-lg"><a href="{% url 'quiz:quiz' %}">Attempt Quiz Now</a></button>          
            </div>
        </div>
    </div>
    
</section>

{% endblock main %}