polling/urls.py
from django.urls import include, path
from . import views

app_name = 'polling'

urlpatterns = [
    path('poll-result/', views.result, name='result'),
    path('poll/', views.poll, name='poll'),
    path('listpoll/', views.poll, name='listpoll'),
	path('', views.index, name='index'),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path
# from LearnAJAX import views as a
# from Quiz import views
from .views import welcom, quiz, result, show
from django.conf import settings
from django.conf.urls.static import static

app_name = 'quiz'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcom, name='welcom'),
    path('quiz/', quiz, name='quiz'),
    path('result/', result, name='result'),
    path('showAnswer/', show, name='show'),
    ]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('chitchat/', include('chitChat.urls')),
    path('artikel/', include('artikel.urls', namespace='artikel')),
    path('forum/', include('forum.urls')),
    path('polling/', include('polling.urls', namespace='polling')),
]

polling/models.py
from django.db import models

act_choices = [
    ('olahraga', 'Olahraga'),
    ('bacabuku', 'Baca Buku'),
    ('bingewatch', 'Binge Watching'),
    ('kuliah', 'Sibuk Kuliah'),
]

# Create your models here.
class PollModel(models.Model):
    activity = models.CharField(
        max_length=30,
        choices=act_choices
    )

    def __str__(self):
        return self.activity

polling/forms.py
from django import forms
from .models import PollModel

act_choices = [
    ('olahraga', 'Olahraga'),
    ('bacabuku', 'Baca Buku'),
    ('bingewatch', 'Binge Watching'),
    ('kuliah', 'Sibuk Kuliah'),
]

class PollForm(forms.ModelForm):
    class Meta:
        model = PollModel
        fields = ['activity']

    activity = forms.CharField(
        widget = forms.RadioSelect(choices=act_choices)
        )

polling/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .forms import PollForm
from .models import PollModel

# Create your views here.
def index(request):
    context = {
        'title' : 'Poll'
    }
    return render(request, 'polling/index.html', context)

def listpoll(request):
    context = {
        'title' : 'Poll',
        'form':PollForm
    }
    return render(request, 'polling/poll.html', context)

def poll(request):
    form = PollForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        cd = form.cleaned_data
        PollModel.objects.create(activity = cd['activity'])
        # form.save()
        return redirect('polling:result')
    context = {
        'title' : 'Poll',
        'form': form
    }
    return render(request, 'polling/poll.html', context)


def result(request):
    option1 = PollModel.objects.filter(activity='olahraga').count()
    option2 = PollModel.objects.filter(activity='bacabuku').count()
    option3 = PollModel.objects.filter(activity='bingewatch').count()
    option4 = PollModel.objects.filter(activity='kuliah').count()

    context = {
        'title' : 'Poll',
        'option1': option1,
        'option2' : option2,
        'option3' : option3,
        'option4' : option4
    }
    return render(request, 'polling/result.html', context)

# 
    

polling/templates/polling/index.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/polling/style.css' %}" />
{% endblock css %} {% block main %}

    <div class="container mx-auto">
		<div class="row justify-content-center text-left jumbotron">
			<div class="col-lg-12 align-self-end">
				<h1><strong>POLL:<br>Bagaimana<br>dengan Anda?</strong></h1>
                <a href="{% url 'polling:listpoll' %}" class="btn btn-primary btn-lg btn-block">Let's poll</a>
			</div>
			
		</div>
	</div>

{% endblock main %}

polling/templates/polling/poll.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/polling/style.css' %}" />
{% endblock css %} {% block main %}

<div class="container m-5 p-5 mx-auto">
    <h1 class="text-center font-weight-bold"><strong>POLL!</strong></h1>
    <div class="card">
        <div class="card-header">
            <h4>Apa yang paling sering kamu lakukan selama #diRumahAja?</h4>
        </div>
        <form method="POST">
            {% csrf_token %}
            <div class="card-body two-col">
                
                    {% for radio in form.activity %}
                        <div class="col-md-6">
                            <div class="card-body">
                                <div>
                                    {{ radio }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    
            </div>
                
        
            <div class="card-footer">
                <button class="btn btn-primary" type="Submit">Vote</button>
                <a href="{% url 'polling:result' %}" class="btn btn-primary" >
                    View Result</a>
            </div>
        </form>
    </div>
</div>
{% endblock main %}

polling/templates/polling/result.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/polling/style.css' %}" />
{% endblock css %} {% block main %}

<div class="container m-5 p-5 mx-auto">
    <h1 class="text-center"><strong>Survey membuktikan...</strong></h1><br>

    <!-- Progress bar -->
    <h4>Olahraga</h4>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ option1 }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{ option1 }}</div>
    </div><br>
    <h4>Baca Buku</h4>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ option2 }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{ option2 }}</div>
    </div><br>
    <h4>Binge Watching</h4>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ option3 }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{ option3 }}</div>
    </div><br>
    <h4>Sibuk Kuliah</h4>
    <div class="progress">
      <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ option4 }}%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">{{ option4 }}</div>
    </div><br>

    <div class="text-right">  
        <a href="{% url 'polling:index' %}" class="btn btn-primary">
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
          </svg>
        </a>
    </div>  
</div>
    
{% endblock main %}