artikel/urls.py
from django.urls import path
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.index, name='index'),
    path('buat-artikel', views.forms, name='forms'),
    path('detail/<slug:slug>', views.detail, name='detail'),
    path('category/<str:category>', views.category, name='category'),
    path('data/', views.data, name='data'),
    path('index2/', views.index2, name='index2'),
    path('data-detail/', views.data_detail, name='data_detail'),
    path('detail2/', views.detail2, name='detail2'),
    path('data-search/', views.data_search, name='data_search'),
    path('search/', views.search, name='search'),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path
# from LearnAJAX import views as a
# from Quiz import views
from .views import welcom, quiz, result, show
from django.conf import settings
from django.conf.urls.static import static

app_name = 'quiz'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcom, name='welcom'),
    path('quiz/', quiz, name='quiz'),
    path('result/', result, name='result'),
    path('showAnswer/', show, name='show'),
    ]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('chitchat/', include('chitChat.urls')),
    path('artikel/', include('artikel.urls', namespace='artikel')),
    path('forum/', include('forum.urls')),
    path('polling/', include('polling.urls', namespace='polling')),
]

artikel/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

# Create your models here.


class Artikel(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.CharField(max_length=25)

    LIST_CATEGORY = (
        ('Berita', 'Berita'),
        ('Teknologi', 'Teknologi'),
        ('Hobi', 'Hobi'),
        ('Kesehatan', 'Kesehatan'),
    )

    category = models.CharField(
        max_length=10, choices=LIST_CATEGORY, default='Berita')

    date_posted = models.DateTimeField(default=timezone.now)
    slug = models.CharField(max_length=150, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(
            "{}-{}".format(self.title, self.author))
        super(Artikel, self).save()

    def __str__(self):
        return "{} - {}".format(self.title, self.author)

artikel/forms.py
from django import forms

from .models import Artikel


class ArtikelForm(forms.ModelForm):

    class Meta:
        model = Artikel
        fields = [
            'title',
            'content',
            'author',
            'category',
        ]
        labels = {
            'title': 'Judul :',
            'content': 'Konten :',
            'author': 'Penulis :',
            'category': 'Kategori :',
        }
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control content-section',
                    'placeholder': 'Judul Artikel'
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control content-section',
                    'placeholder': 'Konten Artikel'
                }
            ),
            'author': forms.TextInput(
                attrs={
                    'class': 'form-control content-section',
                    'placeholder': 'Penulis Artikel'
                }
            ),
            'category': forms.Select(
                attrs={
                    'class': 'form-control content-section'
                }
            ),
        }

artikel/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse

import json
import urllib.request

from .forms import ArtikelForm
from .models import Artikel


def index(request):
    list_artikel = Artikel.objects.all()[::-1]
    page = request.GET.get('page', 1)

    paginator = Paginator(list_artikel, 5)
    try:
        artikel = paginator.page(page)
    except PageNotAnInteger:
        artikel = paginator.page(1)
    except EmptyPage:
        artikel = paginator.page(paginator.num_pages)

    context = {
        'title': 'Artikel',
        'list_artikel': artikel
    }

    return render(request, 'artikel/index.html', context)


def forms(request):
    artikel_form = ArtikelForm(request.POST or None)
    if request.method == 'POST':
        if artikel_form.is_valid():
            artikel_form.save()

            return redirect('artikel:index')

    context = {
        'title': 'Buat Artikel',
        'artikel_form': artikel_form
    }

    return render(request, 'artikel/forms.html', context)


def detail(request, slug):
    artikel = Artikel.objects.get(slug=slug)

    context = {
        'title': artikel.title,
        'artikel': artikel
    }

    return render(request, 'artikel/detail.html', context)


def category(request, category):
    list_artikel = Artikel.objects.filter(category=category)[::-1]
    page = request.GET.get('page', 1)

    paginator = Paginator(list_artikel, 5)
    try:
        artikel = paginator.page(page)
    except PageNotAnInteger:
        artikel = paginator.page(1)
    except EmptyPage:
        artikel = paginator.page(paginator.num_pages)

    context = {
        'title': category,
        'list_artikel': artikel
    }

    return render(request, 'artikel/category.html', context)


def data(request):

    url_news = "https://www.news.developeridn.com/"
    connection = urllib.request.urlopen(url_news)
    js = connection.read()
    info = json.loads(js.decode("utf-8"))

    return JsonResponse(info)


def index2(request):

    context = {
        'title': 'Artikel',
    }

    return render(request, 'artikel/index2.html', context)


def data_detail(request):

    url = request.GET.get(
        'url', 'https://www.cnnindonesia.com/internasional/20200513095240-134-502769/turis-jatuh-usai-nekat-kunjungi-yellowstone-saat-pandemi')

    url_news = "https://www.news.developeridn.com/detail/?url="
    connection = urllib.request.urlopen(url_news + url)
    js = connection.read()
    info = json.loads(js.decode("utf-8"))

    return JsonResponse(info)


def detail2(request):

    url = request.GET.get(
        'url', 'https://www.cnnindonesia.com/internasional/20200513095240-134-502769/turis-jatuh-usai-nekat-kunjungi-yellowstone-saat-pandemi')

    context = {
        'title': 'Artikel',
        'url': url
    }

    return render(request, 'artikel/detail2.html', context)


def data_search(request):

    q = request.GET.get(
        'q', 'indonesia')

    url_news = "https://www.news.developeridn.com/search/?q="
    connection = urllib.request.urlopen(url_news + q)
    js = connection.read()
    info = json.loads(js.decode("utf-8"))

    return JsonResponse(info)


def search(request):

    q = request.GET.get(
        'q', 'indonesia')

    q = 'indonesia' if q == '' else q

    context = {
        'title': q,
        'q': q
    }

    return render(request, 'artikel/index2.html', context)

artikel/templates/artikel/category.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/artikel/style.css' %}" />
{% endblock css %} {% block main %}

<section>
	<div class="container">
		<h1 class="font-weight-bold mb-3">{{title}}</h1>
		{% for artikel in list_artikel %}
		<article class="media content-section">
			<div class="media-body">
				<div class="article-metadata">
					<span class="mr-2">{{artikel.author}}</span>
					<small class="text-muted"
						>{{artikel.date_posted|date:"F d, Y"}}</small
					>
				</div>
				<h2 class="title">
					<a class="title" href="{% url 'artikel:detail' artikel.slug %}"
						>{{artikel.title}}</a
					>
				</h2>
				<p class="article-content">{{artikel.content|truncatechars:350}}</p>
			</div>
		</article>
		{% endfor %}
		{% if list_artikel.has_other_pages %}
		<ul class="pagination">
			{% if list_artikel.has_previous %}
				<li class="page-item">
					<a class="page-link" tabindex="-1" href="?page={{ list_artikel.previous_page_number }}">&laquo;</a>
				</li>
			{% endif %} 
			{% for i in list_artikel.paginator.page_range %} 
				{% if list_artikel.number == i %}
					<li class="page-item active">
						<a class="page-link" href="?page={{ i }}">{{ i }} <span class="sr-only">(current)</span></a>
					</li>
				{% else %}
					<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
				{% endif %} 
			{% endfor %} 
			{% if list_artikel.has_next %}
				<li class="page-item"><a class="page-link" href="?page={{ list_artikel.next_page_number }}">&raquo;</a></li>
			{% endif %}
		</ul>
		{% endif %}
	</div>
</section>

{% endblock main %}

artikel/templates/artikel/detail.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/artikel/style.css' %}" />
{% endblock css %} {% block main %}

<section>
	<div class="container">
		<article class="media content-section">
			<div class="media-body">
				<div class="article-metadata">
					<span class="mr-2">{{artikel.author}}</span>
					<small class="text-muted"
						>{{artikel.date_posted|date:"F d, Y"}}</small
					>
				</div>
				<h2 class="title mb-4">{{artikel.title}}</h2>
				<p class="article-content">{{artikel.content}}</p>
				<a
					class="article-category"
					href="{% url 'artikel:category' artikel.category %}"
					>({{artikel.category}})</a
				>
			</div>
		</article>
	</div>
</section>

{% endblock main %}

artikel/templates/artikel/detail2.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/artikel/style.css' %}" />
{% endblock css %} {% block main %}

<section>
	<div class="container">
		<article id="detail-berita" class="media content-section">

		</article>
	</div>
</section>

{% endblock main %}

{% block script %}
	<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
	<script>
		let url = "{{url}}";
	</script>
    <script src="{% static 'js/artikel/detail.js' %}"></script>
{% endblock script %}

artikel/templates/artikel/forms.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/artikel/style.css' %}" />
{% endblock css %} {% block main %}

<section>
	<div class="container">
		<h1 class="font-weight-bold">{{title}}</h1>
		<div class="forms">
			<form method="POST">
				{% csrf_token %} {% for form in artikel_form %}
				<div class="form-group">{{form.label}} {{form}}</div>
				{% endfor %}
				<button class="btn btn-primary" type="submit">Tambahkan</button>
			</form>
		</div>
	</div>
</section>

{% endblock main %}

artikel/templates/artikel/index.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/artikel/style.css' %}" />
{% endblock css %} {% block main %}

<section>
	<div class="container">
		<h1 class="font-weight-bold mb-3">{{title}}</h1>
		<div class="content-section">
			<h2 class="title">Ingin Menambahkan Artikel?</h2>
			<a class="title" href="{% url 'artikel:forms'%}">Buat Sekarang!</a>
		</div>
		{% for artikel in list_artikel %}
		<article class="media content-section">
			<div class="media-body">
				<div class="article-metadata">
					<span class="mr-2">{{artikel.author}}</span>
					<small class="text-muted"
						>{{artikel.date_posted|date:"F d, Y"}}</small
					>
				</div>
				<h2 class="title">
					<a class="title" href="{% url 'artikel:detail' artikel.slug %}"
						>{{artikel.title}}</a
					>
				</h2>
				<p class="article-content">{{artikel.content|truncatechars:350}}</p>
				<a
					class="article-category"
					href="{% url 'artikel:category' artikel.category %}"
					>({{artikel.category}})</a
				>
			</div>
		</article>
		{% endfor %} 
		{% if list_artikel.has_other_pages %}
		<ul class="pagination">
			{% if list_artikel.has_previous %}
				<li class="page-item">
					<a class="page-link" tabindex="-1" href="?page={{ list_artikel.previous_page_number }}">&laquo;</a>
				</li>
			{% endif %} 
			{% for i in list_artikel.paginator.page_range %} 
				{% if list_artikel.number == i %}
					<li class="page-item active">
						<a class="page-link" href="?page={{ i }}">{{ i }} <span class="sr-only">(current)</span></a>
					</li>
				{% else %}
					<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
				{% endif %} 
			{% endfor %} 
			{% if list_artikel.has_next %}
				<li class="page-item"><a class="page-link" href="?page={{ list_artikel.next_page_number }}">&raquo;</a></li>
			{% endif %}
		</ul>
		{% endif %}
	</div>
</section>

{% endblock main %}

artikel/templates/artikel/index2.html
{% extends 'base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'css/artikel/style.css' %}" />
{% endblock css %}

{% block main %}

<section>
	<div class="container mt-2">
        <div class="row d-flex mb-2">
            <div class="col-4 mr-auto p-2">
                <h1 class="font-weight-bold mb-3">{{title}}</h1>
            </div>
            <input name="search" type="text" class="form-control rounded-pill col-4 p-2" id="searchBar" placeholder="Cari berita...">
            <a id="searchLup" class="fas fa-search p-2"></a>
        </div>
        <div id="berita">

        </div>
	</div>
</section>

{% endblock main %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    {% if title == 'Artikel' %}
        <script src="{% static 'js/artikel/index.js' %}"></script>
    {% else %}
    	<script>
            let q = "{{q}}";
	    </script>
        <script src="{% static 'js/artikel/search.js' %}"></script>
    {% endif %}
{% endblock script %}