artikel/urls.py
from django.urls import path
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.index, name='index'),
    path('buat-artikel', views.forms, name='forms'),
    path('detail/<slug:slug>', views.detail, name='detail'),
    path('category/<str:category>', views.category, name='category'),
    path('data/', views.data, name='data'),
    path('index2/', views.index2, name='index2'),
    path('data-detail/', views.data_detail, name='data_detail'),
    path('detail2/', views.detail2, name='detail2'),
    path('data-search/', views.data_search, name='data_search'),
    path('search/', views.search, name='search'),
]

homepage/urls.py
from django.urls import include, path
from homepage import views

urlpatterns = [
	path('', views.home, name='home'),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path
# from LearnAJAX import views as a
# from Quiz import views
from .views import welcom, quiz, result, show
from django.conf import settings
from django.conf.urls.static import static

app_name = 'quiz'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcom, name='welcom'),
    path('quiz/', quiz, name='quiz'),
    path('result/', result, name='result'),
    path('showAnswer/', show, name='show'),
    ]

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('chitchat/', include('chitChat.urls')),
    path('artikel/', include('artikel.urls', namespace='artikel')),
    path('forum/', include('forum.urls')),
    path('polling/', include('polling.urls', namespace='polling')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'homepage.html', {'title': 'Home'})

homepage/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<!-- Bootstrap CSS -->
			{% include "snippets/bootstrap-css.html" %}

		

		<!-- Google Font -->
		<link
			href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700&display=swap"
			rel="stylesheet"
		/>

		<!-- CSS -->
		<link rel="stylesheet" href="{% static 'css/homepage/style.css' %}" />

		<!-- Block App CSS -->
		{% block css %} {% endblock css %}
		{% block meta %} {% endblock meta %}
		<title>TK D06 | {{title}}</title>
	</head>

	<body>
		{% if title != 'Home' %}
		<!-- Navbar -->
		{% include "navbar.html" %} {% endif %}

		<!-- Block Main-->
		{% block main %} {% endblock main %}

		<!-- jQuery, Popper.js, Bootstrap JS -->
		{% include "snippets/bootstrap-js.html" %}

		{% block script %} {% endblock script %}
		<script
			src="https://kit.fontawesome.com/0ebbe9be0f.js"
			crossorigin="anonymous"
		></script>
	</body>
</html>

homepage/templates/homepage.html
{% include "base.html" %}
{% load static %}


<section id="home">
	<div class="container h-100">
		<div class="row h-100 justify-content-center text-center">
			<div class="col-lg-10 align-self-end">
				<h1 class="home-title font-weight-bold">SELAMAT DATANG</h1>
			</div>
			<div class="col-lg-8 align-self-end mb-5">
				<div class="home-nav">
                    <span><a href="{% url 'artikel:index' %}">Artikel</a></span>
                    <span><a href="/forum">Forum</a></span>
                    <span><a href="/chitchat">Chit-chat</a></span>
					<span><a href="{% url 'quiz:welcom' %}">Quiz</a></span>
					<span><a href="{% url 'polling:index' %}">Poll</a></span>
				</div>
			</div>
		</div>
	</div>
</section>

homepage/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-expand-lg fixed-top navbar-custom">
	<div class="container">
		<a class="navbar-brand" href="/">Home</a>
		<button
			class="navbar-toggler"
			type="button"
			data-toggle="collapse"
			data-target="#navbarNav"
			aria-controls="navbarNav"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'artikel:index' %}">Artikel</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/forum">Forum</a>

				</li>
				<li class="nav-item">
					<a class="nav-link" href="/chitchat">Chit-chat</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'quiz:welcom' %}">Quiz</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'polling:index' %}">Poll</a>
				</li>
			</ul>
		</div>
	</div>
</nav>